
# Обработка исключений. ```try```, ```except```, ```finally```, ```raise```

В этой статье обсудим ошибки и как их "отлавливать" так, чтобы программа не "ломалась". С этой задачей нам поможет справиться блок ```try```.

Ошибки в языке Python принято делить на **синтаксические ошибки** и **исключения**.

## Синтасические ошибки

К синтаксическим ошибкам относятся те, которые не позволяют интерпретатору прочитать код: 

- неверное имя переменной
- скобки, точки, двоеточия в неположенном месте
- пустые блоки: ```def```, ```if```, ```else```, ```class```, ```if```, ```for``` и прочие
- некорректные отступы
- неверное использование именованных аргументов

> Синтаксические ошибки отловить **невозможно**

## Исключения

Все остальные ошибки можно назвать **исключения**. Они возникают как и в процессе написания кода, так и в процессе его тестирования. Ваша задача, как программиста - написать код, который работает без ошибок. Но не все зависит от вас. Программы используются пользователями, а их поведение часто может приводить к ожидаемым и не совсем ошибкам.

---

Например, мы пишем калькулятор, который умеет только делить:

```Python
a = int(input('введите делимое: '))
b = int(input('введите делитель: '))

res = a/b
print(f'частное {res}')
```

Здесь мы можем ожидать два вида исключений:

- ```ValueError```: если пользователь введет букву в качестве одного из чисел
- ```ZeroDivisionError```: если пользователь введет ноль в качестве делителя

Если вторую ошибку можно легко присечь при помощи проверки на равенство нулю, то с первой нужно знать о довольно редко используемом методе ```isdigit()``` и писать дополнительные строчки для приведения строк к числовому типу:

```python
a = input('введите делимое: ')
b = input('введите делитель: ')

if a.isdigit() and b.isdigit():
    a = int(a)
    b = int(b)
    if b != 0:
        res = a/b
        print(f'частное {res}')
    else:
        print("на наоль делить нельзя!")
else:
    print("вводите только числа!")
```

---

## Обработка исключений

Для обработки исключений используются два блока:

- ```try``` - в этот блок оборачиваем код, в котором ожидается исключение
- ```except``` - здесь указывается название ожидаемого исключения и то, что будет происходить при его появлении

```Python
try:
    a = int(input('введите делимое: '))
    b = int(input('введите делитель: '))
    try:
        res = a/b
        print(f'частное {res}')
    except ZeroDivisionError:
        print('на ноль делить нельзя')
except ValueError:
    print("вводите только числа!")
```

---

Также после этих блоков можно прописать блок ```finally```, который сработает в любом случае:

```Python
try:
    a = int(input('введите делимое: '))
    b = int(input('введите делитель: '))
    try:
        res = a/b
        print(f'частное {res}')
    except ZeroDivisionError:
        print('на ноль делить нельзя')
except ValueError:
    print("вводите только числа!")
finally:
    print('работа программы завершена')
```

---

В блоке ```except``` можно указать несколько исключений:

```Python
try:
    a = int(input('введите делимое: '))
    b = int(input('введите делитель: '))
    res = a/b
    print(f'частное {res}')
except (ValueError, ZeroDivisionError):
    print("вводите только числа и не делите на ноль!")
finally:
    print('работа программы завершена')
```

> Вы можете не указывать никаких исключенией после ```except```, в этом случае будут отлавливаться абсолютно все исключения.

## Создание и вызов исключений

Исключения в языке Python исключения являются *объектами* класса ```BaseException```. Встроенные исключения наследуются от этого класса.

Исходя из этого выходит, что мы можем создавать собстенные исключения, наследованные от класса ```Exception```. В качестве примера создадим функцию для вычисления площади прямоугольника и исключение для этой функции. Текст ошибки описывается в магическом методе ```__str__```:

```Python
class SquareException(Exception):
    def __str__(self):
        return "длина или ширина не может быть отрицательной"
```

---

А теперь создадим функцию, которая использует наше исключение. Вызов исключения происходит при помощи ```raise```:

```Python
def calculate_square(a, b):
    if a <= 0 or b <= 0:
        raise SquareException
    return a*b
```

---

Объеденим предыдущие куски кода и вызовем функцию с попыткой вычислить площадь несуществующего прямоугольника:

```Python
class SquareException(Exception):
    def __str__(self):
        return "длина или ширина не может быть отрицательной"

def calculate_square(a, b):
    if a <= 0 or b <= 0:
        raise SquareException
    return a*b
    
print(calculate_square(-3,5))
```

---

Рассмотрим пример посложнее. Предположим, мы создаем класс для создания пользователей:

```Python
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
 
    def display_info(self):
        print(f"Имя: {self.name}  Возраст: {self.age}")
```

---

Теперь определим класс, в котором определим параметры, при которых будет вызываться исключение:

```Python
class PersonAgeException(Exception):
    def __init__(self, age, minage, maxage):
        self.age = age
        self.minage = minage
        self.maxage = maxage
 
    def __str__(self):
        return f"""
        Недопустимое значение: {self.age}.
        Возраст должен быть в диапазоне от {self.minage} до {self.maxage}
        """
```

---

И наконец, совместим эти классы и создадим объект:

```Python
class PersonAgeException(Exception):
    def __init__(self, age, minage, maxage):
        self.age = age
        self.minage = minage
        self.maxage = maxage
 
    def __str__(self):
        return f"""
        Недопустимое значение: {self.age}.
        Возраст должен быть в диапазоне от {self.minage} до {self.maxage}
        """
 
 
class Person:
    def __init__(self, name, age):
        self.__name = name  # устанавливаем имя
        minage, maxage = 1, 110
        if minage < age < maxage:   # устанавливаем возраст, если передано корректное значение
            self.__age = age
        else:                       # иначе генерируем исключение
            raise PersonAgeException(age, minage, maxage)
 
    def display_info(self):
        print(f"Имя: {self.__name}  Возраст: {self.__age}")
 
try:
    tom = Person("Tom", 37)
    tom.display_info()  # Имя: Tom  Возраст: 37
 
    bob = Person("Bob", -23)
    bob.display_info()
except PersonAgeException as e:
    print(e)    # Недопустимое значение: -23. Возраст должен быть в диапазоне от 1 до 110
```

## Список всех исключений Python

![Image title](/assets/exception.png)


```BaseException``` - базовое исключение, от которого берут начало все остальные.

```SystemExit``` - исключение, порождаемое функцией sys.exit при выходе из программы.

```KeyboardInterrupt``` - порождается при прерывании программы пользователем (обычно сочетанием клавиш Ctrl+C).

```GeneratorExit``` - порождается при вызове метода close объекта generator.

---

```Exception``` - а вот тут уже заканчиваются полностью системные исключения (которые лучше не трогать) и начинаются обыкновенные, с которыми можно работать.
            
```StopIteration``` - порождается встроенной функцией next, если в итераторе больше нет элементов.

```ArithmeticError``` - арифметическая ошибка.

```FloatingPointError``` - порождается при неудачном выполнении операции с плавающей запятой. На практике встречается нечасто.
                
```OverflowError``` - возникает, когда результат арифметической операции слишком велик для представления. Не появляется при обычной работе с целыми числами (так как python поддерживает длинные числа), но может возникать в некоторых других случаях.

```ZeroDivisionError``` - деление на ноль.

```AssertionError``` - выражение в функции assert ложно.

```AttributeError``` - объект не имеет данного атрибута (значения или метода).

```BufferError``` - операция, связанная с буфером, не может быть выполнена.

```EOFError``` - функция наткнулась на конец файла и не смогла прочитать то, что хотела.

```ImportError``` - не удалось импортирование модуля или его атрибута.

```LookupError``` - некорректный индекс или ключ.

```IndexError``` - индекс не входит в диапазон элементов.

```KeyError``` - несуществующий ключ (в словаре, множестве или другом объекте).

```MemoryError``` - недостаточно памяти.

```NameError``` - не найдено переменной с таким именем.

```UnboundLocalError``` - сделана ссылка на локальную переменную в функции, но переменная не определена ранее.

```OSError``` - ошибка, связанная с системой:

- ```BlockingIOError```

```ChildProcessError``` - неудача при операции с дочерним процессом.

```ConnectionError``` - базовый класс для исключений, связанных с подключениями:

- ```BrokenPipeError```

- ```ConnectionAbortedError```

- ```ConnectionRefusedError```

- ```ConnectionResetError```

````FileExistsError```` - попытка создания файла или директории, которая уже существует.

```FileNotFoundError``` - файл или директория не существует.


```InterruptedError``` - системный вызов прерван входящим сигналом.


```IsADirectoryError``` - ожидался файл, но это директория.


```NotADirectoryError``` - ожидалась директория, но это файл.


```PermissionError``` - не хватает прав доступа.


```ProcessLookupError``` - указанного процесса не существует.


```TimeoutError``` - закончилось время ожидания.


```ReferenceError``` - попытка доступа к атрибуту со слабой ссылкой.

```RuntimeError``` - возникает, когда исключение не попадает ни под одну из других категорий.


```NotImplementedError``` - возникает, когда абстрактные методы класса требуют переопределения в дочерних классах.

```SyntaxError``` - синтаксическая ошибка.

```IndentationError``` - неправильные отступы.

```TabError``` - смешивание в отступах табуляции и пробелов.

```SystemError``` - внутренняя ошибка.

```TypeError``` - операция применена к объекту несоответствующего типа.

```ValueError``` - функция получает аргумент правильного типа, но некорректного значения.

```UnicodeError``` - ошибка, связанная с кодированием / раскодированием unicode в строках.

```UnicodeEncodeError``` - исключение, связанное с кодированием unicode.

```UnicodeDecodeError``` - исключение, связанное с декодированием unicode.

```UnicodeTranslateError``` - исключение, связанное с переводом unicode.

```Warning``` - предупреждение.
